import type { TeamMember } from "../../types";

export const teamMembers: TeamMember[] = [
  {
    slug: "carlos-goni",
    name: "Carlos Goñi Garrido",
    role: "Partner",
    bio: "Bachelor of Law and Social Sciences from Universidad de Valparaíso and licensed insurance loss adjuster.",
    photo: "https://pub-396ba7766f0a49cba86800f9d74523ad.r2.dev/equipo/carlos.jpg",
    credentials: [
      "Universidad de Valparaíso",
      "Insurance loss adjuster",
      "Partner",
    ],
    education: [
      "Bachelor of Law and Social Sciences, Universidad de Valparaíso",
      "Licensed Insurance Loss Adjuster",
    ],
    languages: ["Spanish", "English"],
  },
  {
    slug: "sebastian-mardones",
    name: "Sebastián Matías Mardones Zúñiga",
    role: "Managing Director",
    bio: "Bachelor of Law and Social Sciences from Universidad Adolfo Ibáñez, with postgraduate training in insurance, employment law and compliance.",
    photo: "https://pub-396ba7766f0a49cba86800f9d74523ad.r2.dev/equipo/sebastian.jpg",
    credentials: [
      "Universidad Adolfo Ibáñez",
      "Postgraduate Diploma in Insurance",
      "Postgraduate Program in Insurance, UBA",
    ],
    education: [
      "Bachelor of Law and Social Sciences, Universidad Adolfo Ibáñez (2010)",
      "Postgraduate Diploma in Insurance, Universidad de Los Andes (2014)",
      "Postgraduate Diploma in Employment Law, Universidad de Chile (2018)",
      "Postgraduate Diploma in Compliance, Universidad Adolfo Ibáñez (2019)",
      "Postgraduate Program in Insurance, Universidad de Buenos Aires (2023)",
    ],
    languages: ["Spanish"],
    email: "smardones@goni-abogados.cl",
  },
  {
    slug: "ruben-nieto",
    name: "Rubén Darío Nieto Santelices",
    role: "Consultant",
    bio: "Consultant to the firm with experience in the insurance and reinsurance market.",
    photo: "https://pub-396ba7766f0a49cba86800f9d74523ad.r2.dev/equipo/ruben.jpg",
    credentials: ["Consultant", "Spanish and English"],
    languages: ["Spanish", "English"],
    email: "rnieto@goni-abogados.cl",
  },
  {
    slug: "josefa-guerrero",
    name: "Josefa María Guerrero Vives",
    role: "Associate",
    bio: "Bachelor of Law and Social Sciences from Universidad Diego Portales, with a postgraduate diploma in Insurance Law and a master's in Employment Law in progress.",
    photo: "https://pub-396ba7766f0a49cba86800f9d74523ad.r2.dev/equipo/josefa.jpg",
    credentials: [
      "Universidad Diego Portales",
      "Postgraduate Diploma in Insurance Law",
      "Master's in Employment Law (in progress)",
    ],
    experience: [
      "Albagli & Zaliasnik — Paralegal (January 2018 - January 2019)",
    ],
    education: [
      "Bachelor of Law and Social Sciences, Universidad Diego Portales (2019)",
      "Postgraduate Diploma in Insurance Law, specializing in General Insurance: Property Damage and Marine Insurance, Pontificia Universidad Católica de Chile (2022)",
      "Master's in Employment Law and Social Security (2025 - 2026, in progress)",
    ],
    languages: ["Spanish", "English"],
    email: "jguerrero@goni-abogados.cl",
    linkedin: "https://www.linkedin.com/in/josefa-mar%C3%ADa-guerrero-vives-734051155/",
  },
  {
    slug: "daniel-lagunas",
    name: "Daniel Alberto Lagunas Pizarro",
    role: "Associate",
    bio: "Associate at Goñi & Cía. Abogados with a track record in court practice and insurance law, with the firm since 2000.",
    photo: "https://pub-396ba7766f0a49cba86800f9d74523ad.r2.dev/equipo/daniel.jpg",
    credentials: [
      "Goñi & Cía. Abogados since 2000",
      "Insurance Law and Marine Insurance",
    ],
    experience: [
      "Sociedad de Cobranzas Soherco Ltda. — Paralegal (1993 - 1995)",
      "Inverca S.A. — Court paralegal and Coordinator (1995 - 2000)",
      "Goñi & Cía. Abogados — Paralegal and Associate (December 2000 to date)",
    ],
    education: [
      "Course in Insurance Law and Marine Insurance, Escuela de Seguros de Chile (2005)",
    ],
    languages: ["Spanish"],
    email: "dlagunas@goniabogados.cl",
    linkedin: "https://www.linkedin.com/in/daniel-lagunas-pizarro-71b13256/",
  },
  {
    slug: "danilo-alvarez",
    name: "Danilo Iván Álvarez Medina",
    role: "Associate",
    bio: "Bachelor of Law and Social Sciences from Universidad Miguel de Cervantes, with experience in court practice.",
    photo: "https://pub-396ba7766f0a49cba86800f9d74523ad.r2.dev/equipo/danilo.jpg",
    credentials: [
      "Universidad Miguel de Cervantes",
      "Court practice experience",
    ],
    experience: [
      "Acción Legal — Paralegal (March - September 2008)",
      "Endress, Israel & Olguin — Paralegal (September 2008 - July 2012)",
    ],
    education: [
      "Bachelor of Law and Social Sciences, Universidad Miguel de Cervantes (2019)",
    ],
    languages: ["Spanish"],
    email: "dalvarez@goniabogados.cl",
  },
  {
    slug: "nicolas-obregon",
    name: "Nicolás Antonio Obregón Soto",
    role: "Associate",
    bio: "Bachelor of Law and Social Sciences from Pontificia Universidad Católica de Chile, specializing in private law and with training in civil litigation.",
    photo: "https://pub-396ba7766f0a49cba86800f9d74523ad.r2.dev/equipo/nicolas.jpg",
    credentials: [
      "Pontificia Universidad Católica de Chile",
      "Specialization in Private Law",
      "Postgraduate Diploma in Civil Litigation (in progress)",
    ],
    experience: [
      "Un Techo para Chile — Internship (March 2024 - May 2024)",
      "URZÚA Abogados — Internship (June 2025 - November 2025)",
    ],
    education: [
      "Bachelor of Law and Social Sciences, Pontificia Universidad Católica de Chile (2025)",
      "Academic Certificate of Specialization in Private Law, Pontificia Universidad Católica de Chile (2025)",
      "Legal English Course, Universidad del Desarrollo (2025)",
      "Postgraduate Diploma in Advanced Procedural Law and Civil Litigation, Pontificia Universidad Católica de Chile (2026, in progress)",
    ],
    languages: ["Spanish", "English"],
    email: "nobregon@goni-abogados.cl",
    linkedin: "https://www.linkedin.com/in/nicolasobre/",
  },
  {
    slug: "antonia-soto",
    name: "Antonia De Los Ángeles Soto Pizarro",
    role: "Associate",
    bio: "Bachelor of Law and Social Sciences from Universidad Diego Portales, with an honors diploma in Public Policy.",
    photo: "https://pub-396ba7766f0a49cba86800f9d74523ad.r2.dev/equipo/antonia.jpg",
    credentials: [
      "Universidad Diego Portales",
      "Honors Diploma in Public Policy",
    ],
    experience: [
      "Álamos, Álvarez & Squella — Internship (April 2023 - July 2023)",
    ],
    education: [
      "Bachelor of Law and Social Sciences, Universidad Diego Portales (December 2024)",
      "Honors Diploma in Public Policy, Universidad Diego Portales (March 2020 - December 2021)",
    ],
    languages: ["Spanish", "English"],
    email: "asoto@goni-abogados.cl",
    linkedin:
      "https://www.linkedin.com/in/antonia-de-los-%C3%A1ngeles-soto-pizarro-077ab9351",
  },
  {
    slug: "edith-munoz",
    name: "Edith Del Carmen Muñoz Cabrales",
    role: "Administration and Finance",
    bio: "Legal technician trained at Instituto Jurídico Canon, in charge of the firm's administration and finance.",
    photo: "https://pub-396ba7766f0a49cba86800f9d74523ad.r2.dev/equipo/edith.jpg",
    credentials: ["Legal technician", "Administration and Finance"],
    education: ["Legal Technician, Instituto Jurídico Canon"],
    languages: ["Spanish"],
    email: "emunoz@goni-abogados.cl",
  },
];
